---
title: "Kernel Mean Matching"
output:
  html_document:
    df_print: paged
---

An `R` implementation of Kernel Mean Matching from [http://www.cs.cmu.edu/~arthurg/papers/covariateShiftChapter.pdf](http://www.cs.cmu.edu/~arthurg/papers/covariateShiftChapter.pdf).  Adapted from [https://github.com/vodp/py-kmm/blob/master/Kernel%20Meam%20Matching.ipynb].

```{r setup}
library(data.table)
library(kernlab)
library(quadprog)

setwd('~/github/bdr/')
source('functions.R')


pew_data = fread('data/pew_data.csv')
pew_data[y_dem == 1, support := '1-Dem']
pew_data[y_rep == 1, support := '2-Rep']
pew_data[y_oth == 1, support := '3-Other']

pew_data[, age_num_imp := as.numeric(age_num)]
pew_data[is.na(age_num_imp), age_num_imp := mean(pew_data$age_num, na.rm = T)]
summary(pew_data[, age_num_imp])

pew_data[, age_scaled := scale(age_num_imp)/5]


#categorize variables
survey_vars = c('demo_mode', 'demo_education', 'demo_phonetype', 'demo_ideology')
file_and_survey_vars = c('demo_sex', 'demo_age_bucket', 'demo_income', 'demo_region', 'demo_race', 'demo_hispanic')
all_vars = names(pew_data)[grepl('demo|^age_scaled', names(pew_data))]
all_vars = all_vars[-which(grepl('demo_state|month_called', all_vars))]
file_only_vars = all_vars[!all_vars %in% c(survey_vars, file_and_survey_vars)]

# set n_bags
n_bags = 30

## get test train sets
testtrain = getTestTrain(data = pew_data
                         , n_holdout = 1000, n_surveyed = 2000, n_matched = 1000
                         , p_surveyed = pew_data$p_surveyed
                         , p_matched = pew_data$p_matched
)
pew_data[, .(.N, mean(y_dem)), .(holdout, surveyed, matched, voterfile)]

```

First we'll make the distributions of the matched survey data match the full file
```{r kmm-1, cache = T}
# set bounds for weights
B = 5.0  # upper bound; B = 1 is the unweighted solution

vars = c(file_and_survey_vars, file_only_vars)

fmla_overlap_vars = as.formula(paste0('~', paste(vars, collapse = '+')))
X = model.matrix(object = fmla_overlap_vars, data = pew_data)  #not all levels

X_matched = X[which(pew_data$matched == 1),]    # data to weight
X_file = X[which(pew_data$voterfile == 1),]  # target

d_matched = as.matrix(dist(X_matched))
median(d_matched)

w_matched = doKMM(X_trn = X_matched, X_tst = X_file, sigma = 0.25, B = 5)  # the smaller sigma is, the more weighting that happens 

# calculate weights
w_matched$weights = (nrow(X_matched)/sum(w_matched$solution)) * w_matched$solution

summary(w_matched$weights)
hist(w_matched$weights)
```
Compare raw and weighted distributions to those of the target
```{r check-dist-1}
data.table(var = colnames(X_file)
           , target = colSums(X_file)/nrow(X_file)
           , matched_raw = colSums(X_matched)/nrow(X_matched)
           , matched_weighted = t(w_matched$weights %*% X_matched/nrow(X_matched))[,1]
)
```


```{r kmm-2, cache = T}
B = 5.0  # upper bound; B = 1 is the unweighted solution

vars = c(survey_vars,file_and_survey_vars)

fmla_survey_vars = as.formula(paste0('~', paste(vars, collapse = '+')))
X = model.matrix(object = fmla_survey_vars, data = pew_data)

X_matched = X[which(pew_data$matched == 1),]    # target
X_matched_weighted = apply(X_matched, 2, function(x) x * w_matched$weights)

X_unmatched = X[which(pew_data$matched == 0 & pew_data$surveyed == 1),]  # data to weight

d_v2 = dist(rbind(X_matched, X_unmatched))
median(d_v2^2)

w_unmatched = doKMM(X_trn = X_unmatched, X_tst = X_matched_weighted, sigma = 0.5, B = 5)

w_unmatched$weights = w_unmatched$solution * (nrow(X_unmatched)/sum(w_unmatched$solution))

summary(w_unmatched$weights)
hist(w_unmatched$weights)
```


Compare raw and weighted distributions to those of the target
```{r check-dist-2}
data.table(var = colnames(X_matched)
           , target_raw = colSums(X_matched)/nrow(X_matched)
           , target_weighted = colSums(X_matched_weighted)/nrow(X_matched_weighted)
           , unmatched_raw = colSums(X_unmatched)/nrow(X_unmatched)
           , unmatched_weighted = t((w_unmatched$weights %*% X_unmatched)/nrow(X_matched))[,1]
)
```


