---
title: "Pew Experiment Results"
author: "Valerie Bradley"
date: "8/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(R.utils)
library(plotROC)

sourceDirectory('~/github/bdr/utils/')

plot_dir = '~/github/bdr/pew-experiment/plots/'
```

# Load results and data
```{r}
load('~/github/bdr/pew-experiment/results/results_20180828.RData')

outcome = gsub('_hat', '', names(results[[1]]))
```

```{r}
###### PREP plot data
plot_data = rbindlist(lapply(names(results), function(r_lab){
  cbind(model = r_lab, results[[r_lab]], pew_data[, .(support, holdout)])
}))
setnames(plot_data, c('model', 'P(Dem)', 'P(Rep)', 'P(Other)', 'actual', 'holdout'))
plot_data
plot_data_melted = melt(plot_data, id.vars = c('model', 'actual', 'holdout'))
#cbind(plot_data_melted, actual = rep(pew_data[, support], length(unique(plot_data_melted$model)) * 3))
```


# Make Crosstabs
```{r xtabs,  results = 'hide'}
models = names(results)
xtab_vars = c(' topline', vars$file_and_survey[!(vars$file_and_survey == 'demo_state')])


## Do xtabs of score
score_xtabs = lapply(models, function(m){
  temp = cbind(' topline' = 1, pew_data, plot_data[model == m,])[holdout == 1, ]
  temp$p_class <- c('1-Dem', '2-Rep', '3-Other')[apply(temp[, .(`P(Dem)`,`P(Rep)`,`P(Other)`)], 1, which.max)]
  
  temp = rbindlist(lapply(xtab_vars, function(v){
    cbind(v, temp[, .(y_hat_dem = mean(`P(Dem)`)
                      , y_hat_rep = mean(`P(Rep)`)
                      , y_hat_oth = mean(`P(Other)`)
                      , y_hat_dem_2way = sum(`P(Dem)`)/sum(`P(Dem)` + `P(Rep)`)
                      , class_rate = mean(p_class == actual)
    ), by = get(v)])
  }))
  setnames(temp, c('var', 'level', paste0('y_hat_', m, c('_dem', '_rep', '_oth', '_dem_2way')), paste0('class_rate_', m)))
})

score_xtabs = Reduce(function(d1, d2) merge(d1, d2, by = c('var', 'level'), all = T), score_xtabs)


## do xtabs of raw data
getXtab = function(var, data){
  tab = data[, .(.N
                 , prop_surveyed = mean(surveyed)
                 , prop_matched = mean(matched)
                 , n_holdout = sum(holdout)
                 , dist_raw = .N/nrow(data)
                 , dist_matched = sum(matched)/sum(data$matched)
                 
                 , surveyed_y_dem = sum(y_dem * surveyed)/sum(surveyed)
                 , matched_y_dem = sum(y_dem * matched)/sum(matched)
                 , voterfile_y_dem = sum(y_dem * voterfile * (matched == 0))/sum(voterfile * (matched == 0))
                 
                 , y_dem = sum(y_dem * holdout)/sum(holdout)
                 , y_rep = sum(y_rep * holdout)/sum(holdout)
                 , y_oth = sum(y_oth * holdout)/sum(holdout)
                 , y_dem_2way = sum(y_dem * holdout)/sum(holdout * as.numeric(y_dem + y_rep > 0))
                 
  ), by = get(var)]
  
  tab = cbind(var, tab)
  return(tab)
}

all_tabs = rbindlist(lapply(xtab_vars, getXtab, data = cbind(' topline' = 1, pew_data)))
setnames(all_tabs, old = c('get'), new = c('level'))

# combine xtabs
all_tabs = merge(all_tabs, score_xtabs, by = c('var', 'level'))


## GET DIFFS

lapply(models, function(m){
  all_tabs[, paste0('error_',m,'_dem') := get(paste0('y_hat_', m, '_dem')) - y_dem]
  all_tabs[, paste0('error_',m,'_rep') := get(paste0('y_hat_', m, '_rep')) - y_rep]
  all_tabs[, paste0('error_',m,'_oth') := get(paste0('y_hat_', m, '_oth')) - y_oth]
  all_tabs[, paste0('error_',m,'_dem_2way') := get(paste0('y_hat_', m, '_dem_2way')) - y_dem]
})

```

```{r}
all_tabs[, c('level', 'y_dem', paste0('y_hat_', models, '_dem')), with = F]
all_tabs[, c('level', paste0('error_', models, '_dem')), with = F]
all_tabs[, c('level', paste0('error_', models, '_dem_2way')), with = F]
```



# Check MSE
```{r}
tab_mse = lapply(results, function(r){
  calcMSE(Y = as.numeric(unlist(pew_data[holdout == 1, which(names(pew_data) %in% outcome), with = F]))
          , Y_pred = as.numeric(unlist(r[which(pew_data[,holdout == 1])]))
  )
})
tab_mse = data.table(cbind(model = names(tab_mse), MSE = round(unlist(tab_mse), 4)))
tab_mse[order(model)]
```

# Check classification rate in holdout set
```{r}
### classification rates
tab_classrate = lapply(results, function(r){
  mean((pew_data$support == c('1-Dem', '2-Rep', '3-Other')[apply(r, 1, which.max)])[pew_data$holdout == 1])
})
tab_classrate = data.table(cbind(model = names(tab_classrate), 'Classification Rate' = round(unlist(tab_classrate), 4)))
tab_classrate[order(model)]
```

# Check topline
```{r}
data.table(models
  , error_dem = as.numeric(all_tabs[level == '1', paste0('error_', models, '_dem'), with = F])
, error_rep = as.numeric(all_tabs[level == '1', paste0('error_', models, '_rep'), with = F])
, error_oth = as.numeric(all_tabs[level == '1', paste0('error_', models, '_oth'), with = F])
, error_dem_2way = as.numeric(all_tabs[level == '1', paste0('error_', models, '_dem_2way'), with = F])
)
```



# Plots
```{r}
# add jitter for unique breaks
plot_data_melted[, value := value + rnorm(nrow(plot_data_melted), 0, 0.000000001)]
plot_data_melted = plot_data_melted[, .(actual, holdout, value, score_decile = cut(value, breaks = quantile(value, probs = seq(0,1,0.1)), labels = 1:10, include.lowest = T))
                                    , by = .(model, variable)]
```


```{r}
###### PLOT: check distributions of predicted probabilities

plot_pred_probs = ggplot(plot_data_melted, aes(x = value, color = actual)) + geom_density() +
  facet_grid(variable ~ model) +
  scale_color_manual(values=c("dodgerblue3", "red3", "forestgreen"), 
                     name="Actual Support") +
  ggtitle("Model predicted probs by actual respondent support")+
  xlab("Predicted probability")

ggsave(filename = paste0(plot_dir, '/plot_pred_probs.png')
       , plot = plot_pred_probs, device = 'png', width = 10, height = 6)
plot_pred_probs
```


```{r}
##### PLOT: check rank-order

plot_data_melted[, actual_ind := as.numeric(gsub('.-', '', actual) == gsub('P[(]|[)]', '', variable))]

plot_deciles = ggplot(plot_data_melted[holdout == 1, .(avg_class = mean(actual_ind)),.(score_decile, model, variable)], aes(x = score_decile, y = avg_class)) + geom_bar(stat = 'identity') +
  facet_grid(variable ~ model) +
  ggtitle("Actual class rate by decile of score - HOLDOUT group")+
  xlab("Score decile")
plot_deciles
ggsave(filename = paste0(plot_dir, '/plot_deciles.png')
       , plot = plot_deciles, device = 'png', width = 10, height = 6)
```


```{r}
##### PLOT: Check calibration

ggplot(plot_data_melted[, .(.N, actual_pct = mean(actual_ind) * 100), .(model, variable, score = floor(value * 100))]) +
  geom_abline(slope = 1, intercept = 0, color = 'grey') +
  geom_point(aes(x = score,  y = actual_pct, size = N, alpha = 0.2)) +
  facet_grid(variable ~ model) +
  ggtitle("Calibration of modeled probabilities") +
  xlab("Modeled probability") +
  ylab("Actual %")
```

```{r}
#### PLOT: ROC curves
plot_roc = ggplot(plot_data_melted) + 
  geom_roc(n.cuts = 0, aes(d = actual_ind, m = value, color = model)) + facet_grid(~variable)
roc_text = calc_auc(plot_roc)
roc_text$model = rep(sort(models), 3)
roc_text$variable = sort(rep(unique(plot_data_melted$variable), length(unique(plot_data_melted$model))))
roc_text$label = paste0(roc_text$model, ": ", round(roc_text$AUC, 3))

plot_roc = plot_roc + geom_text(data = roc_text, aes(x = 1, y = (8-group)/20, label = label, hjust = 1), size = 3) +
  ggtitle("Model ROC curves") + xlab("False positive rate") + ylab("True postitive rate")
plot_roc

ggsave(filename = paste0(plot_dir, '/plot_roc.png')
       , plot = plot_roc, device = 'png', width = 10, height = 4)
```




